/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JOptionPane;
import model.Celula;
import model.Tabuleiro;

/**
 *
 * @author Allan Pereira
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    static Controller controller;
    static Tabuleiro tabuleiro;
    Tabuleiro gabarito;
    public TelaInicial() {
        initComponents();
        controller = new Controller();
        gabarito = controller.gabaritarFimDeJogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8-Puzzle");
        setResizable(false);

        btn11.setMaximumSize(new java.awt.Dimension(40, 40));
        btn11.setMinimumSize(new java.awt.Dimension(40, 40));
        btn11.setPreferredSize(new java.awt.Dimension(40, 40));
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setMaximumSize(new java.awt.Dimension(40, 40));
        btn12.setMinimumSize(new java.awt.Dimension(40, 40));
        btn12.setPreferredSize(new java.awt.Dimension(40, 40));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn13.setMaximumSize(new java.awt.Dimension(40, 40));
        btn13.setMinimumSize(new java.awt.Dimension(40, 40));
        btn13.setPreferredSize(new java.awt.Dimension(40, 40));
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn21.setMaximumSize(new java.awt.Dimension(30, 30));
        btn21.setMinimumSize(new java.awt.Dimension(30, 30));
        btn21.setPreferredSize(new java.awt.Dimension(40, 40));
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn22.setMaximumSize(new java.awt.Dimension(30, 30));
        btn22.setMinimumSize(new java.awt.Dimension(30, 30));
        btn22.setPreferredSize(new java.awt.Dimension(40, 40));
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        btn23.setMaximumSize(new java.awt.Dimension(30, 30));
        btn23.setMinimumSize(new java.awt.Dimension(30, 30));
        btn23.setPreferredSize(new java.awt.Dimension(40, 40));
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });

        btn31.setMaximumSize(new java.awt.Dimension(30, 30));
        btn31.setMinimumSize(new java.awt.Dimension(30, 30));
        btn31.setPreferredSize(new java.awt.Dimension(40, 40));
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });

        btn32.setMaximumSize(new java.awt.Dimension(30, 30));
        btn32.setMinimumSize(new java.awt.Dimension(30, 30));
        btn32.setPreferredSize(new java.awt.Dimension(40, 40));
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });

        btn33.setMaximumSize(new java.awt.Dimension(30, 30));
        btn33.setMinimumSize(new java.awt.Dimension(30, 30));
        btn33.setPreferredSize(new java.awt.Dimension(40, 40));
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnIniciar)))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIniciar)
                .addGap(53, 53, 53))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        try{
            Celula vazia = controller.procurarVazio(tabuleiro);
            if(vazia.getPosicaoX() == 0 && vazia.getPosicaoY() == 1){
                controller.moverParaEsquerda(tabuleiro);
            }else if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 0){
                controller.moverParaCima(tabuleiro);
            }
            atualizaTabuleiro();
        }catch(IndexOutOfBoundsException e){
            
        }
        if(controller.compararTabuleiros(gabarito, tabuleiro)){
            desativarBotoes();
            JOptionPane.showMessageDialog(null, "Você venceu!");
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        tabuleiro = controller.criarTabuleiro();
        controller.exibirTabuleiro(tabuleiro);
        ativarBotoes();
        btn11.setText(tabuleiro.getTabuleiro()[0][0].getValor());
        btn12.setText(tabuleiro.getTabuleiro()[0][1].getValor());
        btn13.setText(tabuleiro.getTabuleiro()[0][2].getValor());
        btn21.setText(tabuleiro.getTabuleiro()[1][0].getValor());
        btn22.setText(tabuleiro.getTabuleiro()[1][1].getValor());
        btn23.setText(tabuleiro.getTabuleiro()[1][2].getValor());
        btn31.setText(tabuleiro.getTabuleiro()[2][0].getValor());
        btn32.setText(tabuleiro.getTabuleiro()[2][1].getValor());
        btn33.setText(tabuleiro.getTabuleiro()[2][2].getValor());
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        try{
            Celula vazia = controller.procurarVazio(tabuleiro);
            if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 1){
                controller.moverParaDireita(tabuleiro);
            }else if(vazia.getPosicaoX() == 0 && vazia.getPosicaoY() == 2){
                controller.moverParaBaixo(tabuleiro);
            }else if(vazia.getPosicaoX() == 2 && vazia.getPosicaoY() == 2){
                controller.moverParaCima(tabuleiro);
            }
            atualizaTabuleiro();
        }catch(IndexOutOfBoundsException e){
            
        }
        if(controller.compararTabuleiros(gabarito, tabuleiro)){
            desativarBotoes();
            JOptionPane.showMessageDialog(null, "Você venceu!");
        }
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        try{
            Celula vazia = controller.procurarVazio(tabuleiro);
            if(vazia.getPosicaoX() == 0 && vazia.getPosicaoY() == 0){
                controller.moverParaBaixo(tabuleiro);
            }else if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 1){
                controller.moverParaEsquerda(tabuleiro);
            }else if(vazia.getPosicaoX() == 2 && vazia.getPosicaoY() == 0){
                controller.moverParaCima(tabuleiro);
            }
            atualizaTabuleiro();
        }catch(IndexOutOfBoundsException e){
            
        }
        if(controller.compararTabuleiros(gabarito, tabuleiro)){
            desativarBotoes();
            JOptionPane.showMessageDialog(null, "Você venceu!");
        }
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed
        try{
            Celula vazia = controller.procurarVazio(tabuleiro);
            if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 0){
                controller.moverParaBaixo(tabuleiro);
            }else if(vazia.getPosicaoX() == 2 && vazia.getPosicaoY() == 1){
                controller.moverParaEsquerda(tabuleiro);
            }
            atualizaTabuleiro();
        }catch(IndexOutOfBoundsException e){
            
        }
        if(controller.compararTabuleiros(gabarito, tabuleiro)){
            desativarBotoes();
            JOptionPane.showMessageDialog(null, "Você venceu!");
        }
    }//GEN-LAST:event_btn31ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        try{
            Celula vazia = controller.procurarVazio(tabuleiro);
            if(vazia.getPosicaoX() == 0 && vazia.getPosicaoY() == 0){
                controller.moverParaDireita(tabuleiro);
            }else if(vazia.getPosicaoX() == 0 && vazia.getPosicaoY() == 2){
                controller.moverParaEsquerda(tabuleiro);
            }else if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 1){
                controller.moverParaCima(tabuleiro);
            }
            atualizaTabuleiro();
        }catch(IndexOutOfBoundsException e){
            
        }
        if(controller.compararTabuleiros(gabarito, tabuleiro)){
            desativarBotoes();
            JOptionPane.showMessageDialog(null, "Você venceu!");
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        try{
            Celula vazia = controller.procurarVazio(tabuleiro);
            if(vazia.getPosicaoX() == 0 && vazia.getPosicaoY() == 1){
                controller.moverParaBaixo(tabuleiro);
            }else if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 0){
                controller.moverParaDireita(tabuleiro);
            }else if(vazia.getPosicaoX() == 2 && vazia.getPosicaoY() == 1){
                controller.moverParaCima(tabuleiro);
            }else if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 2){
                controller.moverParaEsquerda(tabuleiro);
            }
            atualizaTabuleiro();
        }catch(IndexOutOfBoundsException e){
            
        }
        if(controller.compararTabuleiros(gabarito, tabuleiro)){
            desativarBotoes();
            JOptionPane.showMessageDialog(null, "Você venceu!");
        }
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed
        try{
            Celula vazia = controller.procurarVazio(tabuleiro);
            if(vazia.getPosicaoX() == 2 && vazia.getPosicaoY() == 0){
                controller.moverParaDireita(tabuleiro);
            }else if(vazia.getPosicaoX() == 2 && vazia.getPosicaoY() == 2){
                controller.moverParaEsquerda(tabuleiro);
            }else if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 1){
                controller.moverParaBaixo(tabuleiro);
            }
            atualizaTabuleiro();
        }catch(IndexOutOfBoundsException e){
            
        }
        if(controller.compararTabuleiros(gabarito, tabuleiro)){
            desativarBotoes();
            JOptionPane.showMessageDialog(null, "Você venceu!");
        }
    }//GEN-LAST:event_btn32ActionPerformed

    private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed
        try{
            Celula vazia = controller.procurarVazio(tabuleiro);
            if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 2){
                controller.moverParaBaixo(tabuleiro);
            }else if(vazia.getPosicaoX() == 2 && vazia.getPosicaoY() == 1){
                controller.moverParaDireita(tabuleiro);
            }
            atualizaTabuleiro();
        }catch(IndexOutOfBoundsException e){
            
        }
        if(controller.compararTabuleiros(gabarito, tabuleiro)){
            desativarBotoes();
            JOptionPane.showMessageDialog(null, "Você venceu!");
        }
    }//GEN-LAST:event_btn33ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        try{
            Celula vazia = controller.procurarVazio(tabuleiro);
            if(vazia.getPosicaoX() == 1 && vazia.getPosicaoY() == 2){
                controller.moverParaCima(tabuleiro);
            }else if(vazia.getPosicaoX() == 0 && vazia.getPosicaoY() == 1){
                controller.moverParaDireita(tabuleiro);
            }
            atualizaTabuleiro();
        }catch(IndexOutOfBoundsException e){
            
        }
        
        if(controller.compararTabuleiros(gabarito, tabuleiro)){
            desativarBotoes();
            JOptionPane.showMessageDialog(null, "Você venceu!");
        }
    }//GEN-LAST:event_btn13ActionPerformed
    private void atualizaTabuleiro(){
        controller.exibirTabuleiro(tabuleiro);
        btn11.setText(tabuleiro.getTabuleiro()[0][0].getValor());
        btn12.setText(tabuleiro.getTabuleiro()[0][1].getValor());
        btn13.setText(tabuleiro.getTabuleiro()[0][2].getValor());
        btn21.setText(tabuleiro.getTabuleiro()[1][0].getValor());
        btn22.setText(tabuleiro.getTabuleiro()[1][1].getValor());
        btn23.setText(tabuleiro.getTabuleiro()[1][2].getValor());
        btn31.setText(tabuleiro.getTabuleiro()[2][0].getValor());
        btn32.setText(tabuleiro.getTabuleiro()[2][1].getValor());
        btn33.setText(tabuleiro.getTabuleiro()[2][2].getValor());
    }
    
    public void desativarBotoes(){
        btn11.setEnabled(false);
        btn12.setEnabled(false);
        btn13.setEnabled(false);
        btn21.setEnabled(false);
        btn22.setEnabled(false);
        btn23.setEnabled(false);
        btn31.setEnabled(false);
        btn32.setEnabled(false);
        btn33.setEnabled(false);
    }
    
    public void ativarBotoes(){
        btn11.setEnabled(true);
        btn12.setEnabled(true);
        btn13.setEnabled(true);
        btn21.setEnabled(true);
        btn22.setEnabled(true);
        btn23.setEnabled(true);
        btn31.setEnabled(true);
        btn32.setEnabled(true);
        btn33.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btnIniciar;
    // End of variables declaration//GEN-END:variables
}
